require 'grpc'
require 'rpc_services_pb'
require 'macaroon_interceptor.rb'
require 'json'
require 'ostruct'

require 'lightning/version'
require 'lightning/stub'
require 'lightning/node'
require 'lightning/invoice'
